spring.application.name=mscv-usuarios
server.port=8001

spring.datasource.url=jdbc:postgresql://dbbasemicroservices.cxffpognpm3r.us-east-1.rds.amazonaws.com:5432/mscv_usuarios
spring.datasource.username=postgres
spring.datasource.password=3015789795

mscv-cursos.url=${CURSOS_URL:http://10.0.3.162:8002}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

logging.level.org.hibernate.SQL=debug