spring.application.name=mscv-usuarios
server.port=8001

spring.datasource.url=jdbc:postgresql://dpg-d6gqts1r0fns739g7fhg-a.oregon-postgres.render.com:5432/mscv_usuarios
spring.datasource.username=mscv_usuarios_user
spring.datasource.password=e0Pc5aFWSl2hjEemT5p1k0rAqBr1G1xI

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
logging.level.org.hibernate.SQL=debug
