spring.application.name=mscv-cursos

server.port=8002


spring.datasource.url=jdbc:postgresql://dbbasemicroservices.cxffpognpm3r.us-east-1.rds.amazonaws.com:5432/mscv_cursos
spring.datasource.username=postgres
spring.datasource.password=3015789795
mscv-usuarios.url=${USUARIOS_URL:http://10.0.2.47:8001}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

logging.level.org.hibernate.SQL=debug